logging.level.root=INFO
logging.level.page=DEBUG
logging.level.test.helper=DEBUG
logging.level.com.codeborne.selenide=DEBUG
logging.level.io.qameta.allure=DEBUG

logging.pattern.console=%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n